### ISSUE TITLE
Permission to link from drake's official docs?

### ISSUE THREAD

**Issue by wlandau** [b-rodrigues/coolmlproject#2]
Thank you for putting together such a useful set of resources, @b-rodrigues. I think it will definitely help users understand the value of build automation concepts in data science, and you chose a super practical example.

May I link to this repo and the video in drake's official docs? A common question that comes up is how to use drake in custom analysis packages, and I think your materials will help a lot.

**Comment by b-rodrigues** [comment]
Hi Will, of course, please do!

And thank YOU for drake!

**Comment by wlandau** [comment]
Thanks!
